# ./docker-compose.yml
version: "3.5"
services:
  app:
    build: .
    image: "teamhealth:1.0"
services:
  app:
    build: .
    command: bin/rails s Puma -b 0.0.0.0 -p 3000
    # so things like pry work
    tty: true
    stdin_open: true
    volumes:
      # bind-mount your working directory of code
      - .:/home/app
      # attach a volume at /bundle to cache gems
      - bundle:/bundle
      # attach a volume at ./node_modules to cache node modules
      - node-modules:/home/app/node_modules
      # attach a volume at ./tmp to cache asset compilation files
      - tmp:/home/app/tmp
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - BUNDLE_PATH=/bundle
  mysql:
    image: mysql:8.0.21
    command:
      - --default-authentication-plugin=mysql_native_password &
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_development
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  bundle:
    driver: local
  mysql:
    driver: local
  tmp:
    driver: local
  node-modules:
    driver: local
